### ISSUE TITLE
#BUG02:Falta de campo confirmación de password a vista de Registro

### ISSUE THREAD

**Issue by RochettiUriel** [AnimatiWA/AnimatiApp#106]
### Descripción del Bug:
Actualmente, la vista de Registro no cuenta con un campo para confirmar el password. Esto puede llevar a errores de ingreso de contraseñas incorrectas por parte de los usuarios.

### Pasos para Reproducir:
1. Ir a la página de Registro.
2. Llenar todos los campos excepto el de confirmación de password (que no existe).
3. Enviar el formulario con un password incorrecto (porque no hay confirmación).

### Comportamiento Esperado:
- Debe haber un campo de confirmación de password.
- Si las contraseñas no coinciden, mostrar un mensaje de error y no permitir el registro.

### Comportamiento Actual:
- No existe campo de confirmación de password.
- Posibilidad de registrar usuarios con contraseñas mal ingresadas.

### Solución Propuesta:
- Agregar un campo de confirmación de password a la vista de Registro.
- Validar que ambos campos de password coincidan antes de permitir el registro.

### Prioridad:
- Alta (afecta la seguridad y usabilidad del sistema).

### Adjuntos imagen de registro sin la segunda confirmación de la contraseña:
- ![imagen](https://github.com/user-attachments/assets/e899baf3-d538-4531-a3a2-efd017905f23)

**Comment by GabrielNDJ** [comment]
### Resolución:
- Se agregó un campo de confirmación de password en la vista de Registro.
- Se implementó una validación que asegura que el campo de password y el campo de confirmación coincidan.
- Se añadió un mensaje de error que aparece si las contraseñas no coinciden.
- Se probó y verificó que el registro solo se permite cuando ambos campos coinciden.

### Pull Request Asociada:
- Al issues [#BUG02](https://github.com/AnimatiWA/AnimatiApp/issues/106).

### Estado:
- Resuelto y verificado.
