### ISSUE TITLE
#BUG04: Recuperación de contraseña mediante enlace enviado por correo electrónico.

### ISSUE THREAD

**Issue by Nawsper** [AnimatiWA/AnimatiApp#125]
### Descripción del Bug:
Se ha identificado un problema de seguridad en el sistema de login. El usuario, al no poder acceder a su cuenta por inconvenientes con su contraseña, puede solicitar mediante el link "¿Olvidaste tu contraseña?" el envió de un correo electrónico. Mediante este correo le llegara un enlace para reestablecer su contraseña. Actualmente, el correo es enviado correctamente pero no contiene ningún enlace, generando un gran problema para el usuario al no poder reestablecer su contraseña. Esto podría comprometer la seguridad de las cuentas de los usuarios

### Pasos para Reproducir:
1. Navegar a la página de recuperación de contraseña.
2. Ingresar el correo electrónico registrado.
3. Hacer clic en "Enviar correo de recuperación".
4. Ingresar al correo de restablecimiento
5. Hacer clic en enlace de restablecimiento
6. Ingresar nueva contraseña
7. Confirmar

### Comportamiento Esperado:
- El usuario debería recibir un correo con un enlace para cambiar su contraseña.
- El enlace debería redirigir a pantalla para ingresar nueva contraseña.
- Se debería guardar nueva contraseña.

### Comportamiento Actual:
- El usuario recibe el correo para la recuperación de la contraseña a su correo de usuario registrado.
- El correo contiene un mensaje pero no contiene el enlace para la recuperación de la contraseña.

### Solución Propuesta:
- Generar un Enlace Seguro de Restablecimiento: Modificar el proceso de generación del enlace en el backend para incluir un token único y temporal (por ejemplo, válido por 24 horas) asociado al usuario y a la solicitud de restablecimiento.
- Actualizar el Contenido del Correo: Modificar el contenido del correo electrónico de recuperación para incluir el enlace generado.
- Validar el Enlace en el Backend: Al hacer clic en el enlace, el backend debe validar el token. Si el token es válido y no ha expirado, redirigir al usuario a la pantalla de restablecimiento de contraseña.

### Prioridad:
- Alta (afecta la seguridad y usabilidad del sistema).

**Comment by GabrielNDJ** [comment]
### Resolución:

- Se implementó el envío de un código de verificación único y temporal al correo electrónico registrado del usuario para restablecer la contraseña.
- Se actualizó el contenido del correo de recuperación para incluir instrucciones claras sobre cómo utilizar el código de verificación.
- Se añadió una validación en el backend para asegurar que el código sea válido y no haya expirado antes de permitir el restablecimiento de la contraseña.
- Se probó y verificó que el código de verificación permite al usuario restablecer su contraseña de manera segura.

### Pull Request Asociada:

- Al issues #BUG04.

### Estado:

- Resuelto y verificado.
