### ISSUE TITLE
#US11 Gestión de Pedidos

### ISSUE THREAD

**Issue by emir-argcoder** [AnimatiWA/AnimatiApp#50]
## Historia de Usuario #US11: Gestión de Pedidos

*Descripción:*  
Como usuario de la aplicación, quiero poder realizar un pedido y rastrear su estado para saber cuándo llegará mi compra.

*Criterios de Aceptación:*
- El usuario debe poder ver un formulario para realizar el pedido.
- El usuario debe recibir una confirmación después de realizar el pedido.
- El usuario debe poder rastrear el estado de su pedido en tiempo real.

**Comment by Looser3058** [comment]
Tarea Relacionada: [Gestión de Pedidos (#TK10)](50)
