### ISSUE TITLE
#TK11 Gestión de Pedidos

### ISSUE THREAD

**Issue by emir-argcoder** [AnimatiWA/AnimatiApp#51]
### Tareas: Gestión de Pedidos
- *#TK11.1:* Diseñar la interfaz de usuario para realizar pedidos.
- *#TK11.2:* Implementar la funcionalidad de creación de pedidos.
- *#TK11.3:* Integrar la funcionalidad de rastreo de pedidos con la base de datos.
- *#TK11.4:* Implementar notificaciones de estado de pedidos.

**Comment by Looser3058** [comment]
Historia de Usuario Relacionada: [Gestión de Pedidos (#TK10)](50)
